#!/usr/bin/env bash
# One-time setup: create the Red-Team Reviewer agent + environment via the
# Anthropic CLI. Re-run with the `--update` flag after editing YAML files.
#
# Prereqs:
#   - `ant` CLI installed (see https://github.com/anthropics/anthropic-cli)
#   - ANTHROPIC_API_KEY exported
#   - Vault with GitHub MCP OAuth credential created in Console (vault setup
#     is browser-based — see README.md)
#
# Output: writes RED_TEAM_AGENT_ID and RED_TEAM_ENV_ID to ./agents/.env

set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
UPDATE_MODE="${1:-}"

if [[ "$UPDATE_MODE" == "--update" ]]; then
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Error: $ENV_FILE not found. Run setup.sh without --update first."
    exit 1
  fi
  # shellcheck source=/dev/null
  source "$ENV_FILE"

  echo "Updating environment $RED_TEAM_ENV_ID..."
  ENV_VERSION=$(ant beta:environments retrieve --environment-id "$RED_TEAM_ENV_ID" --transform version -r)
  ant beta:environments update --environment-id "$RED_TEAM_ENV_ID" --version "$ENV_VERSION" < red-team-reviewer.environment.yaml > /dev/null
  echo "  ok"

  echo "Updating agent $RED_TEAM_AGENT_ID..."
  AGENT_VERSION=$(ant beta:agents retrieve --agent-id "$RED_TEAM_AGENT_ID" --transform version -r)
  ant beta:agents update --agent-id "$RED_TEAM_AGENT_ID" --version "$AGENT_VERSION" < red-team-reviewer.agent.yaml > /dev/null
  echo "  ok"
  echo
  echo "Done. New agent version pinned automatically on next session create."
  exit 0
fi

# Initial create
echo "Creating environment..."
ENV_ID=$(ant beta:environments create < red-team-reviewer.environment.yaml --transform id -r)
echo "  env_id=$ENV_ID"

echo "Creating agent..."
AGENT_ID=$(ant beta:agents create < red-team-reviewer.agent.yaml --transform id -r)
echo "  agent_id=$AGENT_ID"

# Persist IDs
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -Iseconds). Do not check in.
RED_TEAM_AGENT_ID=$AGENT_ID
RED_TEAM_ENV_ID=$ENV_ID
EOF

echo
echo "Wrote $(pwd)/$ENV_FILE."
echo
echo "Next steps:"
echo "  1. In Anthropic Console -> Vaults, create a vault and add an OAuth"
echo "     credential pointing to https://api.githubcopilot.com/mcp/ (follow"
echo "     GitHub Copilot's OAuth flow). Copy the vault ID."
echo "  2. Export RED_TEAM_VAULT_ID=vlt_... (or add to .env)."
echo "  3. Export GITHUB_TOKEN=ghp_... (fine-grained PAT with Contents:rw on"
echo "     the labspace repo)."
echo "  4. Run: npx tsx run-red-team.ts <idea-id>"
